import{a as f,S as p,i as l}from"./assets/vendor-D9tHNiur.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();f.defaults.baseURL="https://pixabay.com/api/";const d="49133693-4042ac5cb8c0a8ba13ba0f36c";function m(a){return f.get("/",{params:{key:d,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(o=>o.data.hits).catch(o=>(console.error("Помилка:",o),[]))}const i=document.querySelector(".gallery");function g(a){i.innerHTML="";const o=a.map(s=>{const{webformatURL:e,largeImageURL:t,tags:n,likes:h,views:b,comments:v,downloads:w}=s;return`<li class="gallery-item">
      <a href="${t}" class="gallery-link">
            <img src="${e}" alt="${n}" class="gallery-image" width="640" height="360" />
            </a>
            <div class="gallery-info">
	          <p class="gallery-info-name">likes<span class="galery-info-value">${s.likes}</span></p>
	          <p class="gallery-info-name">views<span class="galery-info-value">${s.views}</span></p>
	          <p class="gallery-info-name">comments<span class="galery-info-value">${s.comments}</span></p>
            <p class="gallery-info-name">downloads<span class="galery-info-value">${s.downloads}</span></p>
            </div>
        </li>`}).join("");i.insertAdjacentHTML("beforeend",o),new p(".gallery a",{captionsData:"alt",captionDelay:250,captions:!1}).refresh()}const c=document.querySelector(".form"),y=document.querySelector(".input-form"),u=document.querySelector(".loader");c.addEventListener("submit",a=>{a.preventDefault();const o=y.value.trim();if(o===""){l.show({message:"Поле не може бути порожнім. Введіть текст для пошуку...",messageColor:"white",backgroundColor:"#ef4040",position:"topRight",class:"custom-toast"});return}u.style.display="block",m(o).then(r=>{if(r.length===0){l.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",backgroundColor:"#ef4040",position:"topRight",class:"custom-toast"});return}g(r)}).catch(r=>console.log(r)).finally(()=>{u.style.display="none"}),c.reset()});
//# sourceMappingURL=index.js.map
