import{a as u,S as f,i as l}from"./assets/vendor-D9tHNiur.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();u.defaults.baseURL="https://pixabay.com/api/";const p="49133693-4042ac5cb8c0a8ba13ba0f36c";function m(a){return u.get("/",{params:{key:p,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(s=>s.data.hits).catch(s=>(console.error("Помилка:",s),[]))}const i=document.querySelector(".gallery");function g(a){i.innerHTML="";const s=a.map(r=>{const{webformatURL:e,largeImageURL:t,tags:n,likes:y,views:h,comments:b,downloads:v}=r;return`<li class="gallery-item">
      <a href="${t}" class="gallery-link">
            <img src="${e}" alt="${n}" class="gallery-image" width="640" height="360" />
            </a>
            <div class="gallery-info">
	          <p class="gallery-info-name">likes<span class="galery-info-value">${r.likes}</span></p>
	          <p class="gallery-info-name">views<span class="galery-info-value">${r.views}</span></p>
	          <p class="gallery-info-name">comments<span class="galery-info-value">${r.comments}</span></p>
            <p class="gallery-info-name">downloads<span class="galery-info-value">${r.downloads}</span></p>
            </div>
        </li>`}).join("");i.insertAdjacentHTML("beforeend",s),new f(".gallery a",{captionsData:"alt",captionDelay:250,captions:!1}).refresh()}const c=document.querySelector(".form"),d=document.querySelector(".input-form");c.addEventListener("submit",a=>{a.preventDefault();const s=d.value.trim();if(s===""){l.show({message:"Поле не може бути порожнім. Введіть текст для пошуку...",messageColor:"white",backgroundColor:"#ef4040",position:"topRight",class:"custom-toast"});return}m(s).then(o=>{if(o.length===0){l.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",backgroundColor:"#ef4040",position:"topRight",class:"custom-toast"});return}g(o)}).catch(o=>console.log(o)),c.reset()});
//# sourceMappingURL=index.js.map
